name: Terraform Plan 

on:
  pull_request:
    types: [synchronize, edited]
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: init
      run: terraform init
    steps:
    - name: plan
      run: terraform plan

