name: Terraform Plan 

on:
  pull_request:
    types: [synchronize, edited, opened]
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: init
      run: terraform init
    - name: plan
      run: terraform plan
