name: Terraform Plan 

on:
  pull_request:
    types: [synchronize, edited]
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: pwd test
      run: pwd 
    - name: ls test
      run: ls -al 
    - name: init
      run: terraform init
    - name: plan
      run: terraform plan
